### ISSUE TITLE
Issue getting bot online

### ISSUE THREAD

**Issue by TazharTV** [MoronixProduct3/loaf#2]
Hey! I believe I've configured it correctly, I'm using FireDaemon to run the bot as a service, i've set it up the same as my other working bots however the bot application just won't come online when the service is running. I've created the config.js, copied the template and added the details.

**Comment by MoronixProduct3** [comment]
I don't think the code is currently functional.
The `package.json` file is not specifying the discord api version.
I haven't kept up with the changes, so the api method calls are probably failing.
I don't really have time to fix this in the foreseeable future.
I recommend you check other more reliable bots:
-https://discordbots.org/bot/472911936951156740
-https://discordbots.org/bot/367665720055824384
